---

- hosts: all
  tasks:

  - name: install apache2 package
    apt:
      name: apache2
      state: absent  
  - name: Install php support
    apt:
      name: libapache2-mod-php    
      state: absent
