---
 
 - hosts: all
   become: true
   pre_tasks:
 
 
 - hosts: web_servers
   become: true
   tasks:
 
   - name: install webserver package
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest

   - name: copy html file for site
     tags: apache,apache,apache2,httpd
     copy:
       src: index.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644 
 
 - hosts: db_servers
   become: true
   tasks:
 
   - name: install mariadb server
     apt:
       name: mariadb-server
       state: latest
 
 - hosts: file_servers
   become: true
   tasks:
 
   - name: install samba package
     package:
       name: samba
       state: latest
